# Test `habicon` function using NIC 2019 outputs

Load libraries and package functions

```{r}
devtools::load_all()

# regular checking
#devtools::check()

library(tmap)

```

Read in test data (using RWBL maps)

```{r}
rw_suit <- terra::rast("scratch/test_data/rwbl_hab_use")

# note these are resistance values
rw_conn_raw <- terra::rast("scratch/test_data/rwbl_connect")

# rescale values
rw_conn <- rescale_map(rw_conn_raw)


terra::plot(rw_suit)
terra::plot(rw_conn)

```

Calculate bin maps

```{r}
# using top 20% of suitability/connectivity values
suit_bin <-  bin_map(rw_suit, threshold = quantile(terra::values(rw_suit, na.rm = TRUE), 0.8))
#suit_bin <- bin_map(rw_suit, threshold = 0.75)

# 0.2 because resistance values
corr_bin <- bin_map(rw_conn, threshold = quantile(terra::values(rw_conn, na.rm = TRUE), 0.2))

```

Compare suitability bin map to NIC cores map

```{r}
nic_cores <- sf::read_sf("scratch/test_data/rwbl_core_habitat_patches.shp") |>
  sf::st_make_valid()
  

tmap_mode("view")

qtm(suit_bin) +
  qtm(nic_cores)
```

Overlap when threshold is conservative, most cores included when using the top 20% threshold.

## Patch Priority
Took 3.35 hours on Mac (30m res)

```{r}
start <- Sys.time()

patch <- patch_priority(
  suit = rw_suit,
  suit_bin = suit_bin,
  corr_bin = corr_bin,
  resist = rw_conn,
  d = 422,
  progress = TRUE
)

end <- Sys.time()

end - start
# 1.34 hours
```

Save output

```{r}
terra::writeRaster(terra::rast(patch[1:3]), file = "scratch/test_data/nic_patch_priority_rasters.tif")

write.csv(patch[4], file = "scratch/test_data/nic_patch_priority_table.csv")
```

## Corridor Priority

```{r}
start <- Sys.time()

corridor <- corr_priority(
  suit = rw_suit,
  suit_bin = suit_bin,
  corr_bin = corr_bin,
  resist = rw_conn,
  d = 422,
  progress = TRUE
)

end <- Sys.time()

end - start
# 2.16 hours
```


Save output
```{r}
terra::writeRaster(corridor, file = "scratch/test_data/nic_corridor_priority.tif")
```

